resources:
  - service-name-config
  - department-service
  - hello-world-service
  - auth-service
  - api-gateway
  - notification-service
  - config-sync-service
  - configuration-service
  - ui-frontend-service
