apiVersion: v1
kind: ConfigMap
metadata:
  name: service-name-config
data:
  dept-service-name: dept-webapp-service:3001/dept
  config-service-name: config-service:3002/configuration
  kafka-bootstrap-servers: kafka.kafka.svc.cluster.local:9092