version: "3.8"

services:
  opensearch:
    image: opensearchproject/opensearch:2.9.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true      # disable security
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"   # OpenSearch API
      - "9600:9600"   # Performance analyzer
    networks:
      - efk

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.9.0
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - OPENSEARCH_SECURITY_DISABLED=true
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - "5601:5601"  # Dashboards
    depends_on:
      - opensearch
    networks:
      - efk

  fluent-bit:
    image: fluent/fluent-bit:3.2.10
    container_name: fluent-bit
    volumes:
      - C:/E-Drive/My_Projects/logs:/app-logs          # your Spring logs
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
    depends_on:
      - opensearch
    command: ["fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]
    networks:
      - efk

networks:
  efk:
